[package]
name = "ddnet-account-client-reqwest"
version = "0.4.0"
edition = "2024"
authors = ["Jupeyy"]
license = "MIT OR Apache-2.0"
description = "The client implementation using reqwest as HTTP client."
repository = "https://github.com/ddnet/ddnet-accounts"

[dependencies]
ddnet-account-client-http-fs = { version = "0.4", path = "../ddnet-account-client-http-fs" }
ddnet-account-client = { version = "0.3", path = "../ddnet-account-client" }

async-trait = "0.1"
url = { version = "2", features = ["serde"] }
reqwest = { version = "0.13" }
anyhow = { version = "1", features = ["backtrace"] }
